[01-19 08:00:23] p28894 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:28} INFO - Logging is set up.
[01-19 08:01:31] p29240 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:28} INFO - Logging is set up.
[01-19 08:01:52] p29240 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:82} ERROR - User: asdsad is not registered.
[01-19 09:01:02] p32047 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:28} INFO - Logging is set up.
[01-21 17:11:04] p2452 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:28} INFO - Logging is set up.
[01-21 17:11:58] p2872 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:28} INFO - Logging is set up.
[01-21 17:12:18] p2872 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:82} ERROR - User: asdas is not registered.
[01-21 17:12:40] p2872 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:80} DEBUG - Friend with name: Antonio was just added by Vasil.
[01-21 17:12:44] p2872 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:125} DEBUG - Vasil just sent a new message.
[01-21 17:12:50] p2872 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:125} DEBUG - Vasil just sent a new message.
[01-21 17:12:53] p2872 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:125} DEBUG - Vasil just sent a new message.
[01-21 17:13:28] p2872 {/home/anton/.local/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /friends/1/delete [POST]
Traceback (most recent call last):
  File "/home/anton/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anton/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anton/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/anton/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/anton/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anton/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py", line 90, in delete_friend
    friendship.delete()
  File "/home/anton/school/SoftwareEngineering/Basic-Chat-Application/friendship.py", line 46, in delete
    db.execute('DELETE FROM Messages WHERE friendship_id = ', (self.friendship_id,))
sqlite3.OperationalError: incomplete input
[01-21 17:14:53] p3657 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:28} INFO - Logging is set up.
[01-21 17:15:04] p3657 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:92} DEBUG - Friend with name: Antonio was just deleted from Vasil's list of friends.
[01-21 17:16:34] p3800 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:28} INFO - Logging is set up.
[01-21 17:16:58] p3800 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:77} DEBUG - Friend with name: Vasil was just added by Foncho.
[01-21 17:17:02] p3800 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:77} DEBUG - Friend with name: Antonio was just added by Foncho.
[01-21 17:17:09] p3800 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:122} DEBUG - Foncho just sent a new message.
[01-21 17:17:12] p3800 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:122} DEBUG - Foncho just sent a new message.
[01-21 17:19:05] p4306 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:28} INFO - Logging is set up.
[01-21 17:19:20] p4306 {/home/anton/.local/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /friends/new [POST]
Traceback (most recent call last):
  File "/home/anton/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anton/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anton/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/anton/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/anton/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anton/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py", line 79, in new_friend
    flash('This user is not registered.')
  File "/home/anton/.local/lib/python3.6/site-packages/flask/helpers.py", line 423, in flash
    session["_flashes"] = flashes
  File "/home/anton/.local/lib/python3.6/site-packages/werkzeug/local.py", line 350, in __setitem__
    self._get_current_object()[key] = value
  File "/home/anton/.local/lib/python3.6/site-packages/flask/sessions.py", line 103, in _fail
    "The session is unavailable because no secret "
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
[01-21 17:20:43] p4440 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:29} INFO - Logging is set up.
[01-21 17:20:58] p4440 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:81} ERROR - User: Foncho2 is not registered.
[01-21 17:21:01] p4440 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:81} ERROR - User: chovek is not registered.
[01-21 17:24:07] p4652 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:29} INFO - Logging is set up.
[01-21 17:24:19] p4652 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:81} ERROR - User: sadasd is not registered.
[01-21 17:24:21] p4652 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:81} ERROR - User: asdasd is not registered.
[01-21 17:24:24] p4652 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:78} DEBUG - Friend with name: Vasil was just added by Foncho.
[01-21 17:24:28] p4652 {/home/anton/school/SoftwareEngineering/Basic-Chat-Application/app.py:81} ERROR - User: Vasil2 is not registered.
